<?php

namespace BluesFlix\Repositories;

use BluesFlix\Media\ThumbUploads;
use BluesFlix\Media\Uploads;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use BluesFlix\Repositories\SerieRepository;
use BluesFlix\Models\Serie;
use BluesFlix\Validators\SerieValidator;

/**
 * Class SerieRepositoryEloquent
 * @package namespace BluesFlix\Repositories;
 */
class SerieRepositoryEloquent extends BaseRepository implements SerieRepository
{
    use ThumbUploads, Uploads;


    public function create(array $attributes)
    {
        $model = parent::create(array_except($attributes, 'thumb_file')); // TODO: Change the autogenerated stub
        $this->uploadThumb($model->id, $attributes['thumb_file']);
        return $model;
    }

    public function update(array $attributes, $id)
    {
        $model = parent::update(array_except($attributes, 'thumb_file'), $id);
        if (isset($attributes['thumb_file'])){
            $this->uploadThumb($model->id, $attributes['thumb_file']);
        }
        return $model;
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Serie::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
